name: example workflow
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  TERRAFORM: my-terraform
  ENVIRONMENT: dev
  
jobs:
  my-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: my test step
        id: tst
        run: echo "Hello World"
      - name: checkout my repo
        uses: actions/checkout@v4
  terraform-job:
    runs-on: ubuntu-latest
    steps:
      - name: terraform install
        id: ${{ env.TERRAFORM }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: terraform action
        run: terraform init
